// src/lib/components/Footer/Footer.svelte
<script lang="ts">
	import Button from '$lib/components/Button/Button.svelte';
	import ExternalLinks from '$lib/components/ExternalLinks/ExternalLinks.svelte';
	import ExternalLink from '$lib/components/ExternalLinks/ExternalLink.svelte';
	import './Footer.css';

	export let homeButton = false;
</script>

<footer class="footer">
	{#if homeButton}
		<Button tag="a" href="/" variant="text">Return Home</Button>
	{/if}
	<h2 class="highlight primary h1">Say Hi,</h2>
	<div class="links of-footer">
		<h3 id="email">
			<a href="mailto:hi@noahwbaldwin.me">hi@noahwbaldwin.me</a>
		</h3>
		<ExternalLinks>
			<ExternalLink href="https://github.com/noahbald" icon="github">GitHub</ExternalLink>
			<ExternalLink href="https://www.linkedin.com/in/noahwbaldwin/" icon="linkedin">
				LinkedIn
			</ExternalLink>
			<ExternalLink href="https://www.instagram.com/noahbald/" icon="instagram">
				Instagram
			</ExternalLink>
			<ExternalLink href="spotify:user:12101435749" icon="spotify">Spotify</ExternalLink>
		</ExternalLinks>
	</div>
</footer>

// src/components/footer.tsx
import React from 'react'
import { Link } from 'react-router-dom'

import Button from './button'
import ExternalLinks, { ExternalLink } from './external-links'

import { ReactComponent as GitHub } from './component-assets/footer/github.svg'
import { ReactComponent as LinkedIn } from './component-assets/footer/linkedin.svg'
import { ReactComponent as Instagram } from './component-assets/footer/instagram.svg'
import { ReactComponent as Spotify } from './component-assets/footer/spotify.svg'

import './footer.scss'

export interface FooterProps {
  homeButton?: boolean
}

/**
 * Footer to display at the bottom of every page
 */
const Footer: React.FC<FooterProps> = ({ homeButton }) => (
  <footer className="footer">
    {homeButton && (
      <Button as={Link} type="text" to="/">Return Home</Button>
    )}
    <h2 className="highlight highlight--primary h1">Say Hi,</h2>
    <div className="footer__links">
      <h3 id="email"><a href="mailto:hi@noahwbaldwin.me">hi@noahwbaldwin.me</a></h3>
      <ExternalLinks>
        <ExternalLink
          to="https://github.com/noahbald"
          title="Github"
        >
          <GitHub />
        </ExternalLink>
        <ExternalLink
          to="https://www.linkedin.com/in/noahwbaldwin/"
          title="LinkedIn"
        >
          <LinkedIn />
        </ExternalLink>
        <ExternalLink
          to="https://www.instagram.com/noahbald/"
          title="Instagram"
        >
          <Instagram />
        </ExternalLink>
        <ExternalLink
          to="spotify:user:12101435749"
          title="Spotify"
        >
          <Spotify />
        </ExternalLink>
      </ExternalLinks>
    </div>
  </footer>
)
export default Footer
