// src/lib/components/Gallery/Gallery.svelte
<script lang="ts">
	import { writable } from 'svelte/store';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import Button from '$lib/components/Button/Button.svelte';
	import Card from '$lib/components/Card/Card.svelte';
	import type Projects from '$lib/../__mocks__/api/projects';

	import './Gallery.css';

	// FIXME: This isn't very flexible, but it's not like we need it to be right now
	export let projects: Projects['record'][];

	const INTERVAL_TIMEOUT = 3000;

	let position = writable(0);
	let dragging = writable(false);
	let dragInitialX = writable(0);
	let dragDeltaX = writable(0);
	let interval = writable(-1);

	$: visibleProjects = projects.length
		? Array.from({ length: 4 }, (_, i) =>
				projects.at(((($position + i - 1) % projects.length) + projects.length) % projects.length)
		  )
		: [];

	type TouchOrMouseEvent = MouseEvent | TouchEvent;

	function isTouchEvent(event: TouchOrMouseEvent): event is TouchEvent {
		return event instanceof TouchEvent;
	}

	function handleDragStart(event: TouchOrMouseEvent) {
		const { pageX, button } = isTouchEvent(event)
			? { pageX: event.touches[0]?.pageX, button: 0 }
			: event;

		if ($dragging || button !== 0) {
			return;
		}
		clearInterval($interval);
		$dragging = true;
		$dragInitialX = pageX;
		$dragDeltaX = pageX;
	}

	function handleDrag(event: TouchOrMouseEvent) {
		const { pageX } = isTouchEvent(event) ? { pageX: event.touches[0]?.pageX } : event;

		if (!$dragging) {
			return;
		}
		$dragDeltaX = pageX;
		event.preventDefault();
		event.stopPropagation();
	}

	function handleDragStop(event: TouchOrMouseEvent, href: string) {
		if (!$dragging) {
			return href;
		}

		const finalDragDeltaX = $dragInitialX - $dragDeltaX;
		const finalDragDeltaXAbs = Math.abs(finalDragDeltaX);
		const direction = Math.sign(finalDragDeltaX);

		$dragging = false;
		$dragInitialX = 0;
		$dragDeltaX = 0;
		if (finalDragDeltaXAbs < 64) {
			goto(href);
			return;
		} else if (finalDragDeltaXAbs < 128) {
			return;
		}

		$position += direction;
		event.preventDefault();
		event.stopPropagation();
	}

	onMount(() => {
		const newInterval = setInterval(() => ($position += 1), INTERVAL_TIMEOUT);
		$interval = newInterval;

		return () => clearInterval($interval);
	});
</script>

<div class="gallery h4">
	<Button
		variant="text"
		icon="arrow-left"
		on:click={() => clearInterval($interval) || ($position -= 1)}
	>
		<span class="sr-only">Previous item in gallery<span /></span></Button
	>
	{#each visibleProjects as { href, title, subtitle, src, alt, uid }, i (`${uid}-${Math.floor(($position + i) / projects.length)}`)}
		{@const iPosition = i - 1}
		{@const opacity = 0 > iPosition || iPosition > 1 ? 0 : 1}

		<!-- FIXME: Looks like button, role is presentation -->
		<div
			class="content of-gallery soft-shadow"
			class:in={opacity || ($dragging && $dragInitialX - $dragDeltaX !== 0)}
			class:dragging={$dragging}
			style:--drag-distance={`${$dragDeltaX - $dragInitialX}px`}
			style:--i-position={iPosition}
			on:click={() => goto(href)}
			on:touchstart={handleDragStart}
			on:mousedown={handleDragStart}
			on:touchmove={handleDrag}
			on:mousemove={handleDrag}
			on:touchend={(e) => handleDragStop(e, href)}
			on:mouseup={(e) => handleDragStop(e, href)}
			on:keydown={(e) => (e.key === 'Enter' || e.key === ' ') && goto(href)}
			role="presentation"
			tab-index={opacity - 1}
		>
			<img {src} {alt} class="image of-gallery" />
			<Card {href} {title}>
				<hgroup class="h4">
					<h3 class="h4"><strong>{title}</strong></h3>
					<span>
						<strong>&nbsp;&mdash;&nbsp;</strong>
						{subtitle}
					</span>
				</hgroup>
			</Card>
		</div>
	{/each}
	<Button
		variant="text"
		icon="arrow-right"
		on:click={() => clearInterval($interval) || ($position += 1)}
	>
		<span class="sr-only">Next item in gallery</span>
	</Button>
</div>

// src/components/gallery.tsx
import React, {
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react'
import { useNavigate } from 'react-router-dom'
import classNames from 'classnames'

import Button from './button'
import Card from './card'
import IProjects from '../data/IProjects'

import arrowLeft from './component-assets/arrow-left.svg'
import arrowRight from './component-assets/arrow-right.svg'

import './gallery.scss'

const INTERVAL_TIMEOUT = 3000

type TouchOrMouseEvent = React.TouchEvent<HTMLDivElement> | React.MouseEvent<HTMLDivElement>

const isTouchEvent = (e: TouchOrMouseEvent): e is React.TouchEvent<HTMLDivElement> => (
  e.nativeEvent instanceof TouchEvent
)

export interface GalleryProps {
  contents: IProjects['record']
  loading?: boolean
}

/**
 * A carousel which displays up to two items at a time
 * Each item of the `Gallery` is an image, title-subtitle pair
 * @example
 * <Gallery
 *  contents={[
 *    {
 *      uid: '1234',
 *      title: 'Example',
 *      subtitle: 'This is an example Gallery',
 *      href: "/",
 *      src: galleryImage,
 *    }
 *  ]}
 * />
 */
const Gallery: React.FC<GalleryProps> = ({
  contents,
  loading,
}) => {
  const [position, setPosition] = useState(0)
  const [dragging, setDragging] = useState(false)
  const [dragInitialX, setDragInitialX] = useState(0)
  const [dragDeltaX, setDragDeltaX] = useState(0)
  const [interval, setInterval] = useState(-1)

  const navigate = useNavigate()

  const visibleContent = useMemo(() => (
    Array.from(new Array(4), (_, i) => contents.at(
      (((position + i - 1) % contents.length) + contents.length) % contents.length,
    ))
  ), [contents, position])

  const changePosition = useCallback((delta: number) => {
    setPosition(position + delta)
  }, [position, setPosition])

  const handleDragStart = React.useCallback((e: TouchOrMouseEvent) => {
    const { pageX, button } = isTouchEvent(e)
      ? { pageX: e.touches[0]?.pageX, button: 0 }
      : { pageX: e.pageX, button: e.button }
    if (!dragging && button === 0) {
      window.clearInterval(interval)
      setDragging(true)
      setDragInitialX(pageX)
      setDragDeltaX(pageX)
    }
  }, [dragging, interval])

  const handleDrag = React.useCallback((e: TouchOrMouseEvent) => {
    const pageX = isTouchEvent(e)
      ? e.touches[0].pageX
      : e.pageX

    if (dragging) {
      setDragDeltaX(pageX)
      e.preventDefault()
      e.stopPropagation()
    }
  }, [dragging])

  const handleDragStop = React.useCallback((e: TouchOrMouseEvent, href: string): void => {
    if (!dragging) {
      return navigate(href)
    }

    const pageX = isTouchEvent(e)
      ? e.touches[0].pageX
      : e.pageX

    const finalDragDeltaX = dragInitialX - pageX

    if (Math.abs(finalDragDeltaX) > 128) {
      changePosition(Math.sign(finalDragDeltaX))
      e.stopPropagation()
      e.preventDefault()
    } else if (Math.abs(finalDragDeltaX) < 64) {
      navigate(href)
    }
    setDragging(false)
  }, [])

  useEffect(() => {
    const newInterval = window.setInterval(() => changePosition(1), INTERVAL_TIMEOUT)
    setInterval(newInterval)
    return () => window.clearInterval(newInterval)
  }, [])

  return (
    <div className={classNames('gallery', { skeleton: loading })}>
      {loading ? (
        <>
          <Button
            as="div"
            type="text"
            aria-label="Previous item in gallery"
          />
          <div className="gallery__content soft-shadow" style={{ transform: 'translateX(calc(64px + (100% + 64px) * 0))' }}>
            <div className="gallery__image" />
            <Card>
              <h4>
                &nbsp;
              </h4>
            </Card>
          </div>
          <div className="gallery__content soft-shadow" style={{ transform: 'translateX(calc(64px + (100% + 64px) * 1))' }}>
            <div className="gallery__image" />
            <Card>
              <h4>
                &nbsp;
              </h4>
            </Card>
          </div>
          <Button
            as="div"
            type="text"
            aria-label="Next item in gallery"
          />
        </>
      ) : (
        <>
          <Button
            type="text"
            icon={arrowLeft}
            onClick={() => {
              changePosition(-1)
              window.clearInterval(interval)
            }}
            aria-label="Previous item in gallery"
          />
          {visibleContent.map((item, i) => {
            const positionOverflow = Math.floor(position + i) / contents.length
            const iPosition = i - 1
            const opacity = iPosition < 0 || iPosition > 1 ? 0 : 1
            const translateX = `translateX(calc(${dragging ? dragDeltaX - dragInitialX : 0}px + 64px + (100% + 64px) * ${iPosition}))`

            return item && (
              <div
                key={item.uid + String(positionOverflow)}
                className="gallery__content soft-shadow"
                style={{
                  transform: translateX,
                  transition: dragging ? 'none' : undefined,
                  opacity: dragging && (dragInitialX - dragDeltaX !== 0) ? 1 : opacity,
                }}
                onClick={() => navigate(item.href)}
                onTouchStart={handleDragStart}
                onTouchMove={handleDrag}
                onTouchEnd={(e) => handleDragStop(e, item.href)}
                onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && navigate(item.href)}
                role="presentation"
                tabIndex={opacity - 1}
              >
                <img src={item.src} alt="" className="gallery__image" />
                <Card
                  to={item.href}
                  toTitle={item.title}
                >
                  <h4>
                    <strong>{item.title}</strong>
                    &nbsp;&mdash;&nbsp;
                    {item.subtitle}
                  </h4>
                </Card>
              </div>
            )
          })}
          <Button
            type="text"
            icon={arrowRight}
            onClick={() => {
              changePosition(1)
              window.clearInterval(interval)
            }}
            aria-label="Next item in gallery"
          />
        </>
      )}
    </div>
  )
}
export default Gallery
