// src/lib/components/Header/Header.svelte
<script lang="ts">
	import Card from '$lib/components/Card/Card.svelte';
	import type Button from '$lib/components/Button/Button.svelte';

	import './Header.css';

	export interface $$Slots {
		'call-to-action': typeof Button;
	}

	export let heading: string;
	export let src: string;
	export let title: string;
	export let subtitle: string;
</script>

<header class="header h1">
	<div class="image soft-shadow">
		{#if src.endsWith('.webm')}
			<video {src} autoplay loop muted>
				<source {src} alt="" />
			</video>
		{:else}
			<img {src} alt="" />
		{/if}
	</div>
	<h1 class="highlight grey-light">{heading}</h1>
	{#if title}
		<Card class="soft-shadow h4">
			<hgroup>
				<h2 class="h4">
					<strong>{title}</strong>
				</h2>
				<span class="fade delayed">&nbsp;&mdash;&nbsp;</span>
				<span class="fade delayed">
					{#if subtitle}
						<span class="blink">{subtitle}</span>
					{/if}
				</span>
			</hgroup>
			<slot name="call-to-action" />
		</Card>
	{/if}
</header>

// src/components/header.tsx
import React from 'react'

import Card from './card'
import Button from './button'

import './header.scss'

export interface HeaderProps {
  heading?: string
  src?: string
  title?: string
  subtitle?: string
  callToAction?: React.ReactElement<typeof Button>
}

/**
 * Header with image to display at top of page
 * If no title or subtitle is given then no card will render
 */
const Header: React.FC<HeaderProps> = ({
  heading,
  src,
  title,
  subtitle,
  callToAction,
}) => (
  <header className="header">
    <div className="header__image soft-shadow">
      {src?.endsWith('.webm') ? (
        <video src={src} autoPlay loop muted controls={false}>
          <source src={src} type="video/webm" />
        </video>
      ) : (
        <img src={src} alt="" />
      )}
    </div>
    <h1 className="highlight highlight--grey-light">{heading}</h1>
    {title && (
      <Card className="soft-shadow h4">
        <h4>
          <strong>{title}</strong>
          <span className="fade fade--delayed">&nbsp;&mdash;&nbsp;</span>
          <span className="fade fade--delayed">
            {subtitle && (
              <span className="blink">{subtitle}</span>
            )}
          </span>
        </h4>
        {callToAction}
      </Card>
    )}
  </header>
)
export default Header
