// src/lib/components/Markdown/Markdown.svelte
<script lang="ts">
	import { writable } from 'svelte/store';
	import { marked } from 'marked';
	import sanitizeHTML from 'sanitize-html';
	import Button from '$lib/components/Button/Button.svelte';

	import './Markdown.css';

	export let markdown: string;

	let peek = writable(true);

	$: dangerousHTML = markdown && marked.parse(markdown);
	$: sanitizedHTML = sanitizeHTML(dangerousHTML, {
		allowedTags: sanitizeHTML.defaults.allowedTags.concat('img', 'h1', 'h2', 'h3'),
		allowedAttributes: {
			img: ['src', 'alt'],
			a: ['href', 'name', 'target', 'title'],
		},
		selfClosing: ['img'],
	});
</script>

<div class="markdown" class:peek>
	<article class="content of-markdown">
		{@html sanitizedHTML}
	</article>
	{#if peek}
		<Button on:click={() => (peek = false)} class="soft-shadow">Read More</Button>
	{/if}
</div>

// src/components/markdown.tsx
import React, { useState } from 'react'
import { marked } from 'marked'
import sanitizeHtml from 'sanitize-html'
import classNames from 'classnames'

import Button from './button'

import './markdown.scss'
import useWithBucketFile from '../hooks/useWithBucketData'

export interface MarkdownProps {
  loading?: boolean
  markdown?: string
}

/**
 * Render markdown document and style it
 */
const Markdown: React.FC<MarkdownProps> = ({
  loading,
  markdown,
}) => {
  const [peek, setPeek] = useState(true)

  const markdownString = useWithBucketFile(markdown, 'text')

  const dangerousHTML = React.useMemo(() => (
    marked?.parse(typeof markdownString === 'string' ? markdownString : '')
  ), [markdownString])

  const html = React.useMemo(() => ({
    __html: sanitizeHtml(dangerousHTML, {
      allowedTags: sanitizeHtml.defaults.allowedTags.concat('img', 'h1', 'h2', 'h3'),
      allowedAttributes: {
        img: ['src', 'alt'],
        a: ['href', 'name', 'target', 'title'],
      },
      selfClosing: ['img'],
    }),
  }), [dangerousHTML])

  if (loading || markdownString === null) {
    return (
      <div className="markdown peek">
        <article className="markdown__content skeleton">
          <h1>&nbsp;</h1>
          <h2>&nbsp;</h2>
          <br />
          <p>&nbsp;</p>
          <p>
            &nbsp;
            <br />
            &nbsp;
          </p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p>
            &nbsp;
            <br />
            &nbsp;
          </p>
          <br />
          <p>&nbsp;</p>
          <br />
          <h2>nbsp;</h2>
        </article>
      </div>
    )
  }

  return (
    <div className={classNames('markdown', { peek })}>
      {/* eslint-disable-next-line react/no-danger */}
      <article className="markdown__content" dangerouslySetInnerHTML={html} />
      {peek && (
        <Button
          softShadow
          type="solid"
          onClick={() => setPeek(false)}
        >
          Read More
        </Button>
      )}
    </div>
  )
}
export default Markdown
